### ISSUE TITLE
Add sbt-ci-release

### ISSUE THREAD

**Issue by sideeffffect** [alexandru/typelevel-library.g8#4]
consider adding [`sbt-ci-release`](https://github.com/olafurpg/sbt-ci-release) instead of `sbt-git`, `sbt-sonatype`, ...

**Comment by alexandru** [comment]
Thanks for the suggestions. I've setup `sbt-ci-release`, along with a GitHub Actions workflow that does automatic releases.

Can be seen in action at: https://github.com/alexandru/my-typelevel-library
