### ISSUE TITLE
build.sh replaces any installed node_modules

### ISSUE THREAD

**Issue by er1c** [alexandru/typelevel-library.g8#69]
The default `build.sh` has a `git add . && git reset --hard HEAD` that subtly will remove any other installed packages from the build directory.

Scala.js can require you to `npm install jsdom` which  will get nuked and the test runner fail.

This probably needs either a comment or ensure `node_modules` is part of the default `.gitignore`?

I think there is an outstanding Scala.js bug somewhere that requires a local install and doesn't work with the global install of the package.

**Comment by alexandru** [comment]
We should add `node_modules` as part of `.gitignore`.

And we should probably get rid of that `git reset --hard HEAD`.
