### ISSUE TITLE
Use "main" as default branch

### ISSUE THREAD

**Issue by er1c** [alexandru/typelevel-library.g8#74]
@alexandru feel free to close this, if you give thumbs up I'll submit a PR

**Comment by alexandru** [comment]
I love the idea, just did a commit that fixes it.

Alas GitHub doesn't make things easier, had to provide a full walkthrough in the README.

**Comment by alexandru** [comment]
Btw, went ahead and did it b/c it involved settings on my end that you couldn't do anyway. Plus I documented myself to see how hard it is to do, and since I found the settings required, I went ahead and submitted what I've learned in the README.

Sorry for stealing your thunder.

**Comment by er1c** [comment]
That works for me :)  I didn't have any thunder, just pain since I've been modifying the markdown files for new projects.  Thanks!  🎉 🎉 🎉
