### ISSUE TITLE
Add CHANGELOG.md template, use README.md as mdoc index.md 

### ISSUE THREAD

**Issue by alexandru** [alexandru/typelevel-library.g8#76]
Reopening issue, as #73 was closed accidentally. cc @er1c.

On the issue of `.md` links, Cats-Effect has a setup that works, see here how you can provide a `_config.yml` that activates [jekyll-relative-links](https://github.com/benbalter/jekyll-relative-links):

- https://github.com/typelevel/cats-effect/blob/series/2.x/site/src/main/resources/microsite/_config.yml
- https://github.com/typelevel/cats-effect/blob/series/2.x/site/Gemfile#L4

So there isn't much to it.

**Comment by er1c** [comment]
@alexandru Thanks! will test on my projects and reopen PR after done

**Comment by er1c** [comment]
* `CONTRIBUTING.md` is also missing from the microsite (adding for my reference)

**Comment by alexandru** [comment]
>  CONTRIBUTING.md is also missing from the microsite (adding for my reference)

It probably needs to be specified in the listing of `build.sbt`.
